# Generated by Django 3.2.17 on 2023-06-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRD_Title', models.CharField(max_length=50, verbose_name='Product_Title')),
                ('PRD_Description', models.TextField(verbose_name='Description')),
                ('PRD_Category', models.CharField(choices=[('SO', 'Sofa'), ('CH', 'Chair'), ('LI', 'Lighting'), ('BE', 'Bed'), ('TA', 'Table'), ('DI', 'Dining_Table')], max_length=2, verbose_name='Category')),
                ('PRD_Price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product_Price')),
                ('PRD_DiscountPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Product_Discount Price')),
                ('PRD_Image', models.ImageField(blank=True, upload_to='Product', verbose_name='Product Image')),
                ('PRD_Created', models.DateTimeField(verbose_name='Product_Created At')),
                ('PRD_IsNew', models.BooleanField(default=True, verbose_name='New Product')),
                ('PRD_ISBestSeller', models.BooleanField(default=False, verbose_name='Best Seller')),
                ('PRD_Slug', models.SlugField(blank=True, null=True, verbose_name='Product_URL')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
