# Generated by Django 3.2.17 on 2023-06-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_alter_product_prd_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRD_Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_Created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_DiscountPrice',
            new_name='discountPrice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_ISBestSeller',
            new_name='isBestSeller',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_IsNew',
            new_name='isNew',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRD_Title',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('locality', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('zipCode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
