# Generated by Django 3.2.17 on 2023-07-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_relatedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedProduct',
        ),
    ]
