# Generated by Django 4.2.3 on 2023-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_delete_relatedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID'),
        ),
    ]
