# Generated by Django 4.2.3 on 2023-08-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
